version: "3.5"

services:
  centos-wm-install-helper-base:
    build: ./build
    stop_signal: SIGINT
    image: centos-wm-install-helper
    container_name: wm-install-helper-base
    hostname: wm-install-helper-base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../unixShellLib/scripts/:/mnt/scripts/lib/
      - ./scripts/:/mnt/scripts/local/
      - ./runs/:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # Base assets
      - ${H_WMLAB_INSTALLER_BIN}:${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - ${H_WMLAB_PRODUCTS_IMAGE}:${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - ${H_WMLAB_INSTALL_SCRIPT_FILE}:${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - ${H_WMLAB_SUM10_BOOTSTRAP_BIN}:${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_SUM11_BOOTSTRAP_BIN}:${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_FIXES_IMAGE_FILE}:${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - ${H_WMLAB_FIXES_ONLINE_CRED_FILE}:${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      # Integration Platform licenses
      - ${H_WMLAB_LIC_FILE_IP_IS}:${H_WMLAB_LIC_FILE_IP_IS_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_IP_UM}:${H_WMLAB_LIC_FILE_IP_UM_MOUNT_POINT}
      - ${H_WMLAB_LIC_IP_TC_CLUSTERING_IS}:${H_WMLAB_LIC_IP_TC_CLUSTERING_IS_MOUNT_POINT}
      - ${H_WMLAB_LIC_IP_EG}:${H_WMLAB_LIC_IP_EG_MOUNT_POINT}
      - ${H_WMLAB_LIC_MFT_AT}:${H_WMLAB_LIC_MFT_AT_MOUNT_POINT}
      - ${H_WMLAB_LIC_MFT_ATG}:${H_WMLAB_LIC_MFT_ATG_MOUNT_POINT}
      # BPMS licenses
      - ${H_WMLAB_LIC_FILE_BPMS_BR}:${H_WMLAB_LIC_FILE_BPMS_BR_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_ISPLUS}:${H_WMLAB_LIC_FILE_BPMS_ISPLUS_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_MSR}:${H_WMLAB_LIC_FILE_BPMS_MSR_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_UM}:${H_WMLAB_LIC_FILE_BPMS_UM_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_MZNG}:${H_WMLAB_LIC_FILE_BPMS_MZNG_MOUNT_POINT}
      #- ${}:${_MOUNT_POINT}
      # TODO - other licenses according to use case
    environment:
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      - WMLAB_INSTALLER_BIN=${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - WMLAB_PRODUCTS_IMAGE=${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - WMLAB_INSTALL_SCRIPT_FILE=${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SKIP_PATCHING=${H_WMLAB_SKIP_PATCHING}
      - WMLAB_SUM10_BOOTSTRAP_BIN=${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_SUM11_BOOTSTRAP_BIN=${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_FIXES_IMAGE_FILE=${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - WMLAB_FIXES_ONLINE_CRED_FILE=${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      - WMLAB_FIXES_ONLINE=${H_WMLAB_FIXES_ONLINE}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
    entrypoint: ${H_WMLAB_ENTRY_POINT}