version: "3.5"

volumes:
  apigw-install-home: {}
  apigw-sum-home: {}
  apigw-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  apigw:
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_APIGW_HOSTNAME}
    hostname: ${H_WMLAB_apigw_HOSTNAME}
    volumes:
      - apigw-temp:/tmp/
      - apigw-install-home:${H_WMLAB_INSTALL_HOME}
      - apigw-sum-home:/opt/sag/sum/
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_RUNS_FOLDER}:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # from 01.build.000
      - ../01.build.000.commons/lib/unix:${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_WMLAB_INSTALLER_BIN}:${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - ${H_WMLAB_PRODUCTS_IMAGE}:${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - ./scripts/${H_WMLAB_PRODUCTS_VERSION}/install.wmscript.txt:${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - ${H_WMLAB_SUM10_BOOTSTRAP_BIN}:${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_SUM11_BOOTSTRAP_BIN}:${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_FIXES_IMAGE_FILE}:${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - ${H_WMLAB_FIXES_ONLINE_CRED_FILE}:${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
      # License Related
      - ${H_WMLAB_API_GW_A_LICENSE_FILE}:${H_WMLAB_API_GW_A_LICENSE_FILE_MOUNT_POINT}
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### from 01.build.000
      # mount points
      - WMLAB_INSTALLER_BIN=${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - WMLAB_PRODUCTS_IMAGE=${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - WMLAB_INSTALL_SCRIPT_FILE=${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - WMLAB_SUM10_BOOTSTRAP_BIN=${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_SUM11_BOOTSTRAP_BIN=${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_FIXES_IMAGE_FILE=${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - WMLAB_FIXES_ONLINE_CRED_FILE=${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      - WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_FIXES_DATE_TAG=${H_WMLAB_FIXES_DATE_TAG}
      # switches
      - WMLAB_SKIP_PATCHING=${H_WMLAB_SKIP_PATCHING}
      - WMLAB_FIXES_ONLINE=${H_WMLAB_FIXES_ONLINE}
      ### local
      - WMLAB_APIGW_HOSTNAME=${H_WMLAB_APIGW_HOSTNAME}
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/apiGwSetupEntryPoint.sh