version: "3.5"

services:
  builder-analytic-engine-example1:
    image: centos-wm-install-helper
    container_name: builder-analytic-engine-example1
    hostname: builder-analytic-engine-example1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../unixShellLib/scripts/:/mnt/scripts/lib/
      - ./scripts/:/mnt/scripts/local/
      - ./runs/:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - ${H_WMLAB_INSTALLER_BIN}:${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - ${H_WMLAB_PRODUCTS_IMAGE}:${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - ${H_WMLAB_SUM10_BOOTSTRAP_BIN}:${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_SUM11_BOOTSTRAP_BIN}:${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_FIXES_IMAGE_FILE}:${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - ${H_WMLAB_FIXES_ONLINE_CRED_FILE}:${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
    environment:
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      - WMLAB_INSTALLER_BIN=${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - WMLAB_PRODUCTS_IMAGE=${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - WMLAB_WM_INSTALL_HOME=${H_WMLAB_WM_INSTALL_HOME}
      - WMLAB_SKIP_PATCHING=${H_WMLAB_SKIP_PATCHING}
      - WMLAB_SUM10_BOOTSTRAP_BIN=${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_SUM11_BOOTSTRAP_BIN=${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_FIXES_IMAGE_FILE=${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - WMLAB_FIXES_ONLINE_CRED_FILE=${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      - WMLAB_FIXES_ONLINE=${H_WMLAB_FIXES_ONLINE}
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/setupEntryPoint.sh