version: "3.5"

volumes:
  mws-install-home: {}
  mws-sum-home:
    driver_opts:
      type: tmpfs
      device: tmpfs
  mws-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
    n1:
      external: false
services:
  mws:
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-mwsserver
    hostname: mwsserver
    networks:
      n1:
        aliases:
          - mwsserver
    volumes:
      - ../unixShellLib/scripts/:/mnt/scripts/lib/
      - mws-temp:/tmp/
      - mws-install-home:${H_WMLAB_INSTALL_HOME}
      - mws-sum-home:/opt/sag/sum/
      - ${H_RUNS_FOLDER}:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - ./scripts/:/mnt/scripts/local/
    environment:
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      # Setup related
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
    ports:
      - "${H_WMLAB_MWS_PORT}:8585"
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/mws/mwsNormalEntryPoint.sh
