version: "3.8"

networks:
    n1:
      external: false
services:
  optimize:
    image: o4p-ae-server-${H_WMLAB_PRODUCTS_VERSION}
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_PRODUCTS_VERSION}-o4p
    hostname: o4p-ae-server
    volumes:
      - ../unixShellLib/scripts/:/mnt/scripts/lib/
      - ./scripts/:/mnt/scripts/local/
      - ${H_RUNS_FOLDER}:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # give config
      - ./conf/:/mnt/conf/
    networks:
      n1:
        aliases:
          - o4p-ae-server
    environment:
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
    ports:
      - ${H_WMLAB_AE_CONFIG_PORT}:15000
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/o4p-ae/entrypoint.sh